// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-indicators.js
// Contains ALL World Bank indicators for instant (0ms) loading
// Total indicators: 29556
// Generated at: 2026-07-19T07:36:18.038Z

import indicatorsJson from './indicators-data.json';

export interface WBTopic {
  id: number;
  name: string;
  icon: string;
}

export interface WBIndicator {
  id: string;
  name: string;
  sourceNote: string;
}

export const WB_TOPICS: WBTopic[] = indicatorsJson.topics as WBTopic[];

export const WB_INDICATORS_BY_TOPIC: Record<number, WBIndicator[]> = indicatorsJson.byTopic as any;

export const WB_ALL_INDICATORS: WBIndicator[] = indicatorsJson.all as WBIndicator[];
